### ISSUE TITLE
Support applying multiple API declarations at once

### ISSUE THREAD

**Issue by pcornish** [apiman/apiman-cli#33]
Following #32, we should support applying multiple API declarations at once.

This should apply to the following scenarios:

* declarative gateway
* declarative manager
* generate headless gateway configuration

**Comment by pcornish** [comment]
@msavy work underway in https://github.com/apiman/apiman-cli/tree/feature/merge-declarations

**Comment by msavy** [comment]
Awesome. Thanks for the heads up.

**Comment by outofcoffee** [comment]
#32 is merged, so I'm going to close this issue in favour of a PR.
