### ISSUE TITLE
script interpreted by sh which doesn't understand [[ in if statements.

### ISSUE THREAD

**Issue by datagenn** [apiman/apiman-cli#8]
Steps to reproduce (Linux)..

Download zip file, unzip, enter folder, then..

> root@test>./gradlew clean build
> :clean UP-TO-DATE
> :compileJava
> :processResources
> :classes
> :jar
> :assemble
> :compileTestJava
> Download https://repo1.maven.org/maven2/org/rnorth/duct-tape/duct-tape/1.0.4/duct-tape-1.0.4.pom
> Download https://repo1.maven.org/maven2/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.pom
> Download https://repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.pom
> Download https://repo1.maven.org/maven2/org/objenesis/objenesis/2.1/objenesis-2.1.pom
> Download https://repo1.maven.org/maven2/org/objenesis/objenesis-parent/2.1/objenesis-parent-2.1.pom
> Download https://repo1.maven.org/maven2/org/rnorth/duct-tape/duct-tape/1.0.4/duct-tape-1.0.4.jar
> Download https://repo1.maven.org/maven2/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar
> Download https://repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.jar
> Download https://repo1.maven.org/maven2/org/objenesis/objenesis/2.1/objenesis-2.1.jar
> :processTestResources
> :testClasses
> :test
> :check
> :build
> 
> BUILD SUCCESSFUL
> 
> Total time: 5.4 secs
> 
> This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.9/userguide/gradle_daemon.html
> root@test>ls -al
> total 96
> drwxr-xr-x  7 root root  4096 Feb  6 16:33 .
> drwxr-xr-x 25 root root  4096 Feb  6 16:32 ..
> -rwxr-xr-x  1 root root   449 Feb  2 23:46 apiman
> -rw-r--r--  1 root root   150 Feb  2 23:46 apiman.bat
> drwxr-xr-x  9 root root  4096 Feb  6 16:33 build
> -rw-r--r--  1 root root  2089 Feb  2 23:46 build.gradle
> -rw-r--r--  1 root root  1565 Feb  2 23:46 CHANGELOG.md
> drwxr-xr-x  4 root root  4096 Feb  2 23:46 examples
> -rw-r--r--  1 root root    29 Feb  2 23:46 .gitignore
> drwxr-xr-x  3 root root  4096 Feb  2 23:46 gradle
> drwxr-xr-x  3 root root  4096 Feb  6 16:33 .gradle
> -rwxr-xr-x  1 root root  4971 Feb  2 23:46 gradlew
> -rw-r--r--  1 root root  2314 Feb  2 23:46 gradlew.bat
> -rw-r--r--  1 root root 10173 Feb  2 23:46 LICENSE
> -rw-r--r--  1 root root   551 Feb  2 23:46 NOTICE
> -rw-r--r--  1 root root  8852 Feb  2 23:46 README.md
> -rw-r--r--  1 root root   630 Feb  2 23:46 settings.gradle
> drwxr-xr-x  4 root root  4096 Feb  2 23:46 src
> -rw-r--r--  1 root root   262 Feb  2 23:46 .travis.yml
> root@test>./apiman
> ./apiman: 7: ./apiman: [[: not found
> ./apiman: 22: ./apiman: [[: not found
> Error: Unable to access jarfile ./build/libs/apiman-cli.jar
> root@test>

Then adapt file apiman to replace shebang **sh** with **bash**.

Then a gradle problem is seen when apiman file is invoked..

> root@test>./apiman
> ./gradlew: 154: ./gradlew: Syntax error: "(" unexpected
> root@test>

**Comment by outofcoffee** [comment]
Fixed in https://github.com/apiman/apiman-cli/pull/9
